name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install root dependencies
        run: npm install

      - name: Install client dependencies
        working-directory: client
        run: npm install

      - name: Build client
        run: npm run client:build

      - name: Build executables
        run: npm run build:all

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/file-dedup-tool-win
            dist/file-dedup-tool-linux
            dist/file-dedup-tool-linux-arm
            dist/file-dedup-tool-alpine
            dist/file-dedup-tool-alpine-arm
            dist/file-dedup-tool-linux-static
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          body: "Auto-generated release for version ${{ github.ref_name }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}